name: Streamlit
description: CDSW Dell Streamlit example
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2024-07-08"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: cdsw/install_dependencies.py
    kernel: python3
    cpu: 1
    memory: 2

  - type: start_application
    name: Streamlit App
    subdomain: streamlit
    script: cdsw/launch_app.py
    short_summary: Start Streamlit application
    environment_variables:
      TASK_TYPE: START_APPLICATION
